language: emacs-lisp
sudo: false
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - cask install
env:
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.3-travis
script:
  - emacs --version
  - cask build
  - cask clean-elc
  - cask exec ert-runner
  - |
    cask emacs --batch \
    --eval "(require 'package)" \
    --eval "(push '(\"melpa\" . \"http://melpa.org/packages/\") package-archives)" \
    --eval "(package-initialize)" \
    --eval "(package-refresh-contents)" \
    -l package-lint.el \
    -f package-lint-batch-and-exit exercism.el
